insert into products_main (name, price, currency, image, location_id) values ('Bolognese Spaghetti', 4.49, '$', 'assets/img/gallery/burger-king/bolognese-spaghetti.png', 1);
insert into products_main (name, price, currency, image, location_id) values ('Aburi Sushi', 2.19, '$', 'assets/img/gallery/burger-king/aburi-sushi.png', 1);
insert into products_main (name, price, currency, image, location_id) values ('Caesar Salad', 8, '$', 'assets/img/gallery/burger-king/caesar-salad.png',1);
insert into products_main (name, price, currency, image, location_id) values ('Cheese Burger', 1.89, '$', 'assets/img/gallery/burger-king/cheese-burger.png',1);
insert into products_main (name, price, currency, image, location_id) values ('Dancake', 6.49, '$', 'assets/img/gallery/burger-king/dancake.png',1);
insert into products_main (name, price, currency, image, location_id) values ('Pepsi', 0.99, '$', 'assets/img/gallery/burger-king/pepsi.png',1);
insert into products_main (name, price, currency, image, location_id) values ('Prosciutto Pizza', 13.89, '$', 'assets/img/gallery/burger-king/prosciutto-pizza.png',1);
insert into products_main (name, price, currency, image, location_id) values ('Pumpkin Soup', 3.39, '$', 'assets/img/gallery/burger-king/pumpkin-soup.png',1);
insert into products_main (name, price, currency, image, location_id) values ('Caprese Salad', 6.79, '$', 'assets/img/gallery/dominos-pizza/caprese-salad.png',2);
insert into products_main (name, price, currency, image, location_id) values ('Filipino Spaghetti', 6.29, '$', 'assets/img/gallery/dominos-pizza/filipino-spaghetti.png',2);
insert into products_main (name, price, currency, image, location_id) values ('Funfetti Cake', 2.99, '$', 'assets/img/gallery/dominos-pizza/funfetti-cake.png',2);
insert into products_main (name, price, currency, image, location_id) values ('Miso Soup', 3, '$', 'assets/img/gallery/dominos-pizza/miso-soup.png',2);
insert into products_main (name, price, currency, image, location_id) values ('Pepperoni Pizza', 10.99, '$', 'assets/img/gallery/dominos-pizza/pepperoni-pizza.png',2);
insert into products_main (name, price, currency, image, location_id) values ('Sprite', 0.99, '$', 'assets/img/gallery/dominos-pizza/sprite.png',2);
insert into products_main (name, price, currency, image, location_id) values ('Supreme Veggie Burger', 3.49, '$', 'assets/img/gallery/dominos-pizza/supreme-veggie-burger.png',2);
insert into products_main (name, price, currency, image, location_id) values ('Temari Sushi', 3, '$', 'assets/img/gallery/dominos-pizza/temari-sushi.png',2);
insert into products_main (name, price, currency, image, location_id) values ('Chef Salad', 8.49, '$', 'assets/img/gallery/kentucky-fried-chicken/chef-salad.png',3);
insert into products_main (name, price, currency, image, location_id) values ('Fanta', 0.99, '$', 'assets/img/gallery/kentucky-fried-chicken/fanta.png',3);
insert into products_main (name, price, currency, image, location_id) values ('Hamburger', 1.99, '$', 'assets/img/gallery/kentucky-fried-chicken/hamburger.png',3);
insert into products_main (name, price, currency, image, location_id) values ('Oreo Cake', 6.49, '$', 'assets/img/gallery/kentucky-fried-chicken/oreo-cake.png',3);
insert into products_main (name, price, currency, image, location_id) values ('Salami Pizza', 10, '$', 'assets/img/gallery/kentucky-fried-chicken/salami-pizza.png',3);
insert into products_main (name, price, currency, image, location_id) values ('Spicy Spaghetti', 4, '$', 'assets/img/gallery/kentucky-fried-chicken/spicy-spaghetti.png',3);
insert into products_main (name, price, currency, image, location_id) values ('Uramaki Sushi', 3.10, '$', 'assets/img/gallery/kentucky-fried-chicken/uramaki-sushi.png',3);
insert into products_main (name, price, currency, image, location_id) values ('Vegetable Soup', 2.70, '$', 'assets/img/gallery/kentucky-fried-chicken/vegetable-soup.png',3);
insert into products_main (name, price, currency, image, location_id) values ('Cola', 0.99, '$', 'assets/img/gallery/mcDonalds/cola.png',4);
insert into products_main (name, price, currency, image, location_id) values ('Falafel Burger', 2.70, '$', 'assets/img/gallery/mcDonalds/falafel-burger.png',4);
insert into products_main (name, price, currency, image, location_id) values ('Gunkan Maki Sushi', 2.50, '$', 'assets/img/gallery/mcDonalds/gunkan-maki-sushi.png',4);
insert into products_main (name, price, currency, image, location_id) values ('Italian Salad', 9.50, '$', 'assets/img/gallery/mcDonalds/italian-salad.png',4);
insert into products_main (name, price, currency, image, location_id) values ('Margherita Pizza', 8, '$', 'assets/img/gallery/mcDonalds/margherita-pizza.png',4);
insert into products_main (name, price, currency, image, location_id) values ('Meaty Spaghetti', 5.99, '$', 'assets/img/gallery/mcDonalds/meaty-spaghetti.png',4);
insert into products_main (name, price, currency, image, location_id) values ('Thai Soup', 4, '$', 'assets/img/gallery/mcDonalds/thai-soup.png',4);
insert into products_main (name, price, currency, image, location_id) values ('Toffes Cake', 2.70, '$', 'assets/img/gallery/mcDonalds/toffes-cake.png',4);
insert into products_main (name, price, currency, image, location_id) values ('Angel Cake', 6, '$', 'assets/img/gallery/papa-johns-pizza/angel-cake.png',5);
insert into products_main (name, price, currency, image, location_id) values ('Cajun Spaghetti', 6.99, '$', 'assets/img/gallery/papa-johns-pizza/cajun-spaghetti.png',5);
insert into products_main (name, price, currency, image, location_id) values ('Chicken Burger', 3, '$', 'assets/img/gallery/papa-johns-pizza/chicken-burger.png',5);
insert into products_main (name, price, currency, image, location_id) values ('Cobb Salad', 5.40, '$', 'assets/img/gallery/papa-johns-pizza/cobb-salad.png',5);
insert into products_main (name, price, currency, image, location_id) values ('Mushroom Pizza', 11.5, '$', 'assets/img/gallery/papa-johns-pizza/mushroom-pizza.png',5);
insert into products_main (name, price, currency, image, location_id) values ('Oshi Sushi', 2.99, '$', 'assets/img/gallery/papa-johns-pizza/oshi-sushi.png',5);
insert into products_main (name, price, currency, image, location_id) values ('Red Bull', 5, '$', 'assets/img/gallery/papa-johns-pizza/red-bull.png',5);
insert into products_main (name, price, currency, image, location_id) values ('Spinach Soup', 2.99, '$', 'assets/img/gallery/papa-johns-pizza/spinach-soup.png',5);
insert into products_main (name, price, currency, image, location_id) values ('Ambrosia Salad', 7, '$', 'assets/img/gallery/subway/ambrosia-salad.png',6);
insert into products_main (name, price, currency, image, location_id) values ('Apple Cake', 5.99, '$', 'assets/img/gallery/subway/apple-cake.png',6);
insert into products_main (name, price, currency, image, location_id) values ('Apple Juice', 1.5, '$', 'assets/img/gallery/subway/apple-juice.png',6);
insert into products_main (name, price, currency, image, location_id) values ('Chakin Sushi', 3.49, '$', 'assets/img/gallery/subway/chakin-sushi.png',6);
insert into products_main (name, price, currency, image, location_id) values ('Fish Burger', 3.5, '$', 'assets/img/gallery/subway/fish-burger.png',6);
insert into products_main (name, price, currency, image, location_id) values ('Linguine Spaghetti', 5, '$', 'assets/img/gallery/subway/linguine-spaghetti.png',6);
insert into products_main (name, price, currency, image, location_id) values ('Minestrone Soup', 3.5, '$', 'assets/img/gallery/subway/minestrone-soup.png',6);
insert into products_main (name, price, currency, image, location_id) values ('Shrimp Scampi Pizza', 7, '$', 'assets/img/gallery/subway/shrimp-scampi-pizza.png',6);
insert into products_main (name, price, currency, image, location_id) values ('Fattoush Salad', 9.99, '$', 'assets/img/gallery/taco-bell/fattoush-salad.png',7);
insert into products_main (name, price, currency, image, location_id) values ('Funnel Cake', 3.99, '$', 'assets/img/gallery/taco-bell/funnel-cake.png',7);
insert into products_main (name, price, currency, image, location_id) values ('Lemonade', 0.89, '$', 'assets/img/gallery/taco-bell/lemonade.png',7);
insert into products_main (name, price, currency, image, location_id) values ('Mexican Pizza', 12, '$', 'assets/img/gallery/taco-bell/mexican-pizza.png',7);
insert into products_main (name, price, currency, image, location_id) values ('Onion Burger', 3, '$', 'assets/img/gallery/taco-bell/onion-burger.png',7);
insert into products_main (name, price, currency, image, location_id) values ('Tarator Soup', 3.5, '$', 'assets/img/gallery/taco-bell/tarator-soup.png',7);
insert into products_main (name, price, currency, image, location_id) values ('Temaki Sushi', 2.9, '$', 'assets/img/gallery/taco-bell/temaki-sushi.png',7);
insert into products_main (name, price, currency, image, location_id) values ('Bucatini Spaghetti', 3.99, '$', 'assets/img/gallery/taco-bell/bucatini-spaghetti.png',7);
insert into products_main (name, price, currency, image, location_id) values ('Butter Burger', 2, '$', 'assets/img/gallery/wendys/butter-burger.png',8);
insert into products_main (name, price, currency, image, location_id) values ('Butternut Squash Soup', 4.39, '$', 'assets/img/gallery/wendys/butternut-squash-soup.png',8);
insert into products_main (name, price, currency, image, location_id) values ('Ebi Sushi', 3.6, '$', 'assets/img/gallery/wendys/ebi-sushi.png',8);
insert into products_main (name, price, currency, image, location_id) values ('King Cake', 4.8, '$', 'assets/img/gallery/wendys/king-cake.png',8);
insert into products_main (name, price, currency, image, location_id) values ('Mixed Fruit Juice', 2, '$', 'assets/img/gallery/wendys/mixed-fruit-juice.png',8);
insert into products_main (name, price, currency, image, location_id) values ('Panzanella Salad', 9, '$', 'assets/img/gallery/wendys/panzanella-salad.png',8);
insert into products_main (name, price, currency, image, location_id) values ('Red Wine Spaghetti', 4, '$', 'assets/img/gallery/wendys/red-wine-spaghetti.png',8);
insert into products_main (name, price, currency, image, location_id) values ('Seafood Pizza', 13.99, '$', 'assets/img/gallery/wendys/seafood-pizza.png', 8);
